spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelmanagement
    username: root
    password: 1379
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: update
    show-sql: true
